#!/bin/bash
#
# build_app
# Copyright (C) 2024, 2025, 2026
# Terrapane Corporation
#
# This script will build the AES Crypt application for Mac.
#
# Location of key files:
#     build/aescrypt_cli/build/src/aescrypt - the AES Crypt executable
#     ../AES Crypt.app - the application package created from the Script Editor
#
# Arguments may be passed to the script that become CMake arguments
# for building.
#

# Specify which version of AES Crypt to build (git tag)
AES_CRYPT_VERSION=v4.6.0
BUILD_NUMBER=1

# Set the root of the Terrapane source repositories
if [ -z "${TERRAPANE_SOURCE_URI}" ] ; then
    TERRAPANE_SOURCE_URI=https://github.com/terrapane
fi

aescrypt_repo="${TERRAPANE_SOURCE_URI}/aescrypt_cli.git"
aescrypt_app="../AES Crypt.app"
aescrypt_binary="build/aescrypt_cli/build/src/aescrypt"

# Derive the full release/build information to insert into the plist
AES_CRYPT_RELEASE=${AES_CRYPT_VERSION#v}
if [ -n "$BUILD_NUMBER" ] ; then
    AES_CRYPT_RELEASE=${AES_CRYPT_RELEASE}.${BUILD_NUMBER}
else
    AES_CRYPT_RELEASE=${AES_CRYPT_RELEASE}.0
fi

# Switch directories to where this script resides
cd $( dirname "${BASH_SOURCE[0]}" ) || exit 1

# Ensure there isn't already an AES Crypt App file in the parent directory
if [ -e "$aescrypt_app" ] ; then
    echo "The AES Crypt application already exists in $aescrypt_app"
    exit 1
fi

# Ensure cmake is installed
which cmake >/dev/null 2>/dev/null || {
    echo cmake is not install, but is required
    exit 1
}

# Ensure make is installed
which make >/dev/null 2>/dev/null || {
    echo make is not install, but is required
    exit 1
}

# Ensure git is installed
which git >/dev/null 2>/dev/null || {
    echo git is not install, but is required
    exit 1
}

# Build the AES Crypt executable
if [ -d build ] ; then
    echo "The ./build directory exists; remove it"
    exit 1
fi
mkdir -p build || exit 1
git clone --depth=1 --branch=$AES_CRYPT_VERSION --single-branch \
          $aescrypt_repo build/aescrypt_cli
cd build/aescrypt_cli
cmake -S . -B build \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_EXE_LINKER_FLAGS:STRING="-Wl,-no_warn_duplicate_libraries -Wl,-x -Wl,-dead_strip" \
    -DCMAKE_CXX_FLAGS:STRING="-Wpedantic -Wextra -Werror -Wall -flto" \
    -DCMAKE_OSX_ARCHITECTURES:STRING="x86_64;arm64" \
    ${@+"$@"}
cmake --build build --parallel
cd ../..

# Ensure the AES Crypt executable is in place
if [ ! -f "$aescrypt_binary" ] ; then
    echo "The AES Crypt CLI application did not appear to build"
    rm -fr build
    exit 1
fi

# Compile the application
osacompile -o "$aescrypt_app" src/aescrypt-gui.applescript || exit 1

# Ensure the AES Crypt App was created
if [ ! -e "$aescrypt_app" ] ; then
    echo "The AES Crypt application failed to build in $aescrypt_app"
    rm -fr build
    exit 1
fi

# Notify user that files are being put in place
echo Updating the application...

# Copy the plist file into place, replacing the version tag
cat src/Info.plist.template | sed s/AESCRYPT_VERSION_TAG/${AES_CRYPT_RELEASE}/ > "$aescrypt_app"/Contents/Info.plist || exit 1
plutil -convert binary1 "$aescrypt_app"/Contents/Info.plist || exit 1

# Put the application icons into place
iconutil -c icns resources/app_icon.iconset -o "$aescrypt_app"/Contents/Resources/droplet.icns || exit 1
iconutil -c icns resources/aescrypt_paper.iconset -o "$aescrypt_app"/Contents/Resources/aescrypt_paper.icns || exit 1
iconutil -c icns resources/aescrypt_lock.iconset -o "$aescrypt_app"/Contents/Resources/aescrypt_lock.icns || exit 1

# Put the AES Crypt binary into place
cp $aescrypt_binary "$aescrypt_app"/Contents/MacOS/ || exit 1
rm -fr build

echo The application package has been updated

